### ISSUE TITLE
MIME Header Breaks

### ISSUE THREAD

**Issue by samrocks1011** [chrj/smtpd#16]
Any way to support Mime Multipart header

**Comment by Supme** [comment]
Use https://pkg.go.dev/mime and https://pkg.go.dev/mime/multipart

**Comment by samrocks1011** [comment]
@Supme  I have used the above library to Print the MIME and send mail but at the end some characters are missing and give Missing Boundary Error.


![Screenshot_218](https://user-images.githubusercontent.com/9513217/208685172-3cacce9d-9651-4723-b51d-9c1bcf119ea2.png)

**Comment by Supme** [comment]
The beginning of the content should start "--"+boundary
The end of the content should end "--"+boundary+"--"
[Example](https://github.com/Supme/smtpSender/blob/master/builder.go#L26)

**Comment by samrocks1011** [comment]
@Supme  I am using postfix content_filter to pass the mail to smtpd.go library. After Parsing the data and applying the policy I use SendMail function to send the mail to the recipient.  When sending using sendMail ( Converting String to bytes), the data is sent with missing boundary or just skip the HTML part before the missing boundary. 
I have not modified any core library of the code so i do not know want is causing this issue.

**Comment by samrocks1011** [comment]
@Supme   The issue is resolved.  I looped the mail twice in the Send trigger, due to which the function AddReceivedLine was called twice. AddReceivedLine function is used to add "Received: from" in the header. After I rectify the issue and now the mail is going perfectly after the policy is applied.
